---
title: 'Using Sensitivity Analyses to Approximate Total COVID-19 Infections: State and County level in the United States, March 2021 - March 2022'
author: 'Quinn White'
date: 'May 2023'
institution: 'Smith College'
division: 'Mathematics and Natural Sciences'
advisor: 'Ben Baumer'
altadvisor: 'Nicholas Reich'
department: 'Statistical and Data Sciences'
degree: 'Bachelor of Arts'
knit: bookdown::render_book
site: bookdown::bookdown_site
params:
  'Install needed packages for {pioneerdown}': True
output:
  pioneerdown::thesis_pdf: default 
  pioneerdown::thesis_gitbook: default 
abstract: '`r if(knitr:::is_latex_output()) paste(readLines(here::here("thesis/prelims", "00-abstract.Rmd")), collapse = "\n  ")`'
acknowledgements: |
  This project would not have been possible without the the incredible mentorship I received from Professor Ben Baumer at Smith College and Professor Nick Reich at University of Massachusetts Amherst. To begin, Ben, you were essential for getting this project off the ground. In fact, your involvement begins well before that. Sitting in your class my first year of college was the first time I became really excited about coding and data science, which has certainly shaped the path I am on today. The skills I learned in your classes translated directly into research contexts: in particular, the organization to structure a long-term coding project like this, the ability to address questions via coding, and the importance of thinking through how to put together effective data visualizations. This background enabled me to have research experiences as an undergraduate that have motivated me to pursue graduate school.  
  
  Nick, I would like to thank you for making this thesis experience better than I ever could have imagined. From the first meeting we had, it was clear to me that I was incredibly lucky to get the chance to work with you this year, and the experience has meant more to me than I can fully express here. I have learned so much from our conversations along the way on how to think deeply about the questions that arose, and I would always leave our meetings excited to look further into the ideas we discussed. This experience has made me truly appreciate how much mentorship shapes a research experience, and has made me excited to engage in further research in graduate school. 
  
  Beyond advising me on this project, I also really appreciate that you welcomed me to join lab meetings for your research group. On that note, I would like to thank all members of the Reich lab. Everyone was so welcoming and kind from the very start -- I was taken aback when one member, Martha, offered to give me rides over to University of Massachusetts to join the lab meetings, which was a wonderful way to start the day. I always enjoyed the presentations in these meetings; even if a topic was entirely new to me, I could learn so much by hearing the kinds of questions people asked and concerns they raised. You all helped me grow as a scientist, and I am so grateful for your support.
  
    Lastly, I would like to thank my friends and family, particularly my sister. Sienna, you have been involved from the very first phone call I when shared my idea for this project, and even joined my defense on Zoom. You been so encouraging and have made me laugh throughout the entire process.                                                              
bibliography: "bibliography.bib"
csl: csl/apa.csl
lot: false
lof: false
urlcolor: blue
linkcolor: blue
---

```{r,eval=FALSE,include=FALSE}

bibliography: "`r rbbt::bbt_write_bib('./bibliography.json', keys = bbt_detect_citations('./index.Rmd'), overwrite = TRUE)`"

 list.files(here::here(), pattern ="*.Rmd")
rbbt::bbt_write_bib('bibliography.json', overwrite = TRUE)

rbbt::bbt_write_bib('bibliography.json',
                    keys = rbbt::bbt_detect_citations(
                      list.files(here::here(), 
                                 pattern ='*.Rmd',
                                 full.names=TRUE)),
                    overwrite = TRUE)

```

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of 
metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete the section entirely, or silence them (add # before each line). 

If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.

If you receive a duplicate label error after knitting, make sure to delete the index.Rmd file and then knit again.
-->

```{r include_packages, include=FALSE,eval=FALSE}
options(tinytex.verbose = TRUE)

# This chunk ensures that the pioneerdown package is
# installed and loaded. This pioneerdown package includes
# the template files for the thesis.
if (!require(remotes)) {
  if (params$`Install needed packages for {pioneerdown}`) {
    install.packages("remotes", repos = "https://cran.rstudio.com")
  } else {
    stop(
      paste('You need to run install.packages("remotes")",
            "first in the Console.')
    )
  }
}
if (!require(pioneerdown)) {
  if (params$`Install needed packages for {pioneerdown}`) {
    remotes::install_github("SmithCollege-SDS/pioneerdown")
  } else {
    stop(
      paste(
        "You need to run",
        'remotes::install_github("SmithCollege-SDS/pioneerdown")',
        "first in the Console."
      )
    )
  }
}
library(pioneerdown)
# Set how wide the R output will go
options(width = 70, echo = FALSE)
```

```{r,include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


<!--
The ackowledgements, preface, dedication, and abstract are added into the PDF
version automatically by inputing them in the YAML at the top of this file.
Alternatively, you can put that content in files like 00--prelim.Rmd and
00-abstract.Rmd like done below.
-->

<!-- ```{r eval==!knitr::is_latex_output(), child=here::here("thesis/prelims", "00--prelim.Rmd")}
#eval =!knitr::is_latex_output(), changed because throwing an error upon knitting gitbook
```--> 

```{r eval=!knitr::is_latex_output(), child=here::here("thesis/prelims", "00-abstract.Rmd")}

```

<!-- The {.unnumbered} option here means that the introduction will be 
"Chapter 0." You can also use {-} for no numbers on chapters.
-->
<!-- note to self -- defined command-shift-a to be citation shortcut --> 

