---
title: "State Results"
author: "Quinn White"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    df_print: paged
    code_folding: hide
    css: ../../css/template.css
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 18, fig.height= 12)

library(tidyverse)
library(latex2exp)
library(here)
library(scales)

theme_c <- function(...){ 
   # font <- "Helvetica"   #assign font family up front
    theme_bw() %+replace%    #replace elements we want to change
    
    theme(
      
      
      #text elements
      plot.title = element_text(             #title
                   size = 20,                #set font size
                   face = 'bold',            #bold typeface
                   hjust = .5,
                   vjust = 3),               
      
      plot.subtitle = element_text(          #subtitle
                   size = 14,
                   hjust = .5,
                   face = 'italic',
                   vjust = 3),               #font size
      
      axis.title = element_text(             #axis titles
                   size = 25),               #font size
      
      axis.text.x = element_text(              #axis text
                   size = 18),
      legend.text = element_text(size = 18),
      # t, r, b, l
      plot.margin = unit(c(1,.5,.5,.5), "cm"),
      legend.position = "right",
      strip.text.x = element_text(size = 16, face = "bold", color="white"),
      strip.background = element_rect(fill = "#3E3D3D")
      ) %+replace%
      theme(...)
   
}


```


```{r}


priors_versions <- c("v1", "v2", "v3", "v4")


versions <- tibble(
  version = c("v1", "v2", "v3", "v4"),
  vlabel = factor(
    c( "$Priors\\,Do\\,Not\\,Vary\\,by\\,State\\,and\\,Date$", 
    "$\\beta$ Centered at Emp. Value",
    "$P(S_1|untested)$ and $\\beta$ Centered at Emp. Values",
    "$P(S_1|untested)$ Centered at Emp. Value"),
    levels = c(
        "$Priors\\,Do\\,Not\\,Vary\\,by\\,State\\,and\\,Date$", 
        "$\\beta$ Centered at Emp. Value",
        "$P(S_1|untested)$ Centered at Emp. Value",
        "$P(S_1|untested)$ and $\\beta$ Centered at Emp. Values"
        
    ) )
)


state_corrected_path <- here("analysis/results/adj_biweekly_state/")


################################
# ESTIMATED
################################
dates <- readRDS(here("data/date_to_biweek.RDS")) %>%
  group_by(biweek) 



covidestim <- readRDS(here('data/covidestim/covidestim_biweekly_all_states.RDS')) %>% 
  select(-date)


corrected <- map_df(priors_versions, ~readRDS(
        paste0(state_corrected_path, "adj_",
               .x, 
               ".RDS")) %>% 
          mutate(version = .x)) %>%
  left_join(dates, relationship = "many-to-many") %>% 
  rename(state=fips) %>%
  left_join(versions) %>%
  mutate(state=toupper(state)) %>%
  left_join(covidestim, relationship= "many-to-many")
  




```


# Summarizing Concordance with Covidestim



```{r}

# corrected %>%
#   mutate(in_interval = case_when(
#     exp_cases_lb <= infections & infections <= exp_cases_ub ~ "In Interval",
#     exp_cases_lb  > infections  ~ "Below Interval",
#     exp_cases_ub < infections ~ "Above Interval"
#   )) %>%
#   filter(!is.na(in_interval)) %>%
#   group_by(in_interval, state, vlabel) %>%
#   summarize(n_per_county=n()) %>%
#   group_by(vlabel, in_interval) %>%
#   summarize(n_per_version = sum(n_per_county)) %>%
#   group_by(vlabel) %>%
#   mutate(total = sum(n_per_version)) %>%
#   ungroup() %>%
#   mutate(prop=n_per_version/total)



by_version <- corrected %>%
  mutate(in_interval = case_when(
    exp_cases_lb <= infections & infections <= exp_cases_ub ~ "In Interval",
    exp_cases_lb  > infections  ~ "Below Interval",
    exp_cases_ub < infections ~ "Above Interval"
  )) %>%
  filter(!is.na(in_interval)) %>%
  group_by(in_interval, vlabel) %>%
  summarize(n=n()) %>%
  group_by(vlabel) %>%
  mutate(total = sum(n)) %>%
  mutate(prop=n/total) 

labels <- by_version %>%
  arrange(prop) %>%
  pull(vlabel) %>%
  as.character() %>%
  unique()


by_version %>%
   ggplot(aes(x= fct_reorder(vlabel,prop,max), 
             fill = in_interval, y =prop)) + 
  geom_bar(stat="identity",position="dodge") +
  theme_c() +
  coord_flip()+ scale_fill_manual(values=c("In Interval" = "#79D2AF",
                             "Above Interval" = "#D2AF79",
                      "Below Interval"="#7997D2")) +
  labs(x="", 
       y= "Proportion",
       fill = "Covidestim Median:",
       title = "Proportion Where Covidestim Median\nWas Within, Above, or Below the Median",
       subtitle = "State Level") +
  theme_c() +
  theme(legend.position="right",
          legend.title = element_text(face="bold", size = 15),
          legend.text= element_text( size = 15),
          legend.spacing.y = unit(3, 'pt'),
          axis.text.y = element_text(size = 17, hjust=1)) +
  scale_x_discrete(labels = (TeX(labels)))


ggsave(here('presentation/figure/covidestim_concordance_state.jpeg'), height=8, width=14)

```


# Testing Rate over Time 

```{r}

subset <- corrected %>%
  filter(vlabel == "$Priors\\,Do\\,Not\\,Vary\\,by\\,State\\,and\\,Date$")


subset %>%
  ggplot(aes(x=date, y =total/population))+
  geom_line() +
  facet_wrap(~state) +
  theme_c() +
  labs(title ="Biweekly Testing Rate",
       y = "Total Number of Tests / Population Size")


subset %>%
  ggplot(aes(x=date, y =total/population))+
  geom_line() +
  facet_wrap(~state) +
  theme_c() +
  labs(title ="Biweekly Testing Rate",
       y = "Total Number of Tests / Population Size")

###########################################################################
# plot relationship between ratio of estimated cases to observed 
# against testing rate 
###########################################################################
corrected %>%
  ggplot(aes(x=total/population, y = exp_cases_median/positive)) +
  geom_point(alpha=.008, size=.8) +
  facet_wrap(~vlabel,
               labeller= labeller(vlabel =as_labeller(TeX, default=label_parsed))) +
  theme_c(axis.text.x = element_text(size =9),
          axis.title = element_text(size=16) ) +
  theme(strip.text.x = element_text(size=11, color="white")) +
  scale_y_continuous(n.breaks=10) +
  geom_hline(yintercept=1, linetype=2,color="darkred", alpha=.8, linewidth=.5) +
  labs(y = "Ratio of Estimated Infections to Observed",
       x = "Testing Rate",
       subtitle = "All Time Intervals and All States",
       title = "Relationship Between Testing Rate and\nRatio of Estimated Infections to Observed")+
  scale_x_continuous(limits=c(0,.25), n.breaks=4)


ggsave(here('thesis/figure/testing_rate_ratio.jpeg'), width=11,height=7)

corrected %>%
  ggplot(aes(x=total, y = exp_cases_median)) +
  geom_point(alpha=.008, size=.8) +
  facet_wrap(~vlabel,
               labeller= labeller(vlabel =as_labeller(TeX, default=label_parsed))) +
  theme_c(axis.text.x = element_text(size =9),
          axis.title = element_text(size=16) ) +
  theme(strip.text.x = element_text(size=11, color="white")) +
  scale_y_continuous(n.breaks=10) +
  labs(x = "Total Tests",
       y = "Estimated Infections",
       subtitle = "All Time Intervals and All States",
       title = "Relationship Between Testing Rate and\nEstimated Infections")

```


```{r}
# thinking about student populations

# https://nces.ed.gov/ipeds/TrendGenerator/app/trend-table/2/2?trending=column&rid=6
# Source: U.S. Department of Education, National Center for Education Statistics, Integrated Postsecondary Education Data System (IPEDS), 12-month Enrollment component final data (2001-02 - 2019-20) and provisional data (2020-21).

students <- read_csv(here('data/demographic/student_population.csv'), skip=2, n_max=4)
codes <- read_csv(here('data/demographic/statecodes.csv'))

students <- students %>%
  filter(Year =="2020-21") %>% 
  select(-Total) %>%
  pivot_longer(-c(Year),
               names_to="state",
               values_to="student_population") %>%
  left_join(codes, by= c('state'='state')) %>%
  select(state=code, student_population, state_name = state)

corrected %>%
  select(state,population,positive,total) %>%
  distinct() %>%
  left_join(students) %>%
  ggplot(aes(x=student_population/population, y = total/population)) +
  geom_point()


corrected %>%
 # filter(state!="CA") %>%
  select(state,population,positive,total) %>%
  distinct()%>%
  left_join(students) %>%
  ggplot(aes(x=fct_reorder(state_name, total/population),
             y=total/population,
             fill =student_population/population)) +
  geom_boxplot() +
  scale_fill_binned(type="viridis",
                    n.breaks=8,
                    direction=-1,
                    option="magma") +
  theme_c()+
  theme(legend.text=element_text(size=8),
        legend.title = element_text(size=19)) +
  coord_flip() +
  labs(x="",
       fill = "Ratio of Student Population\nto Census Population",
       y= "Total Number of Tests Over Population Size",
       subtitle =
         "Color by Ratio of Student Population\nto Population Reported in the Census",
       title = "Testing Rate by State Across All 2-Week Intervals") +
  scale_y_continuous(n.breaks =6)



ggsave(here::here(paste0('thesis/figure/college_populations.jpeg')), 
       height=11, width = 11, dpi=400)


corrected %>%
  mutate(testrate=total/population) %>%
  filter(testrate>.25) %>% 
 # filter( abs(testrate - max(testrate)) <=.05) %>%
  select(date,testrate, state) %>%
  distinct() 
  
  
```


# Variant Data

```{r,eval=FALSE}
# 
# test %>%
#   flatten()
# 
# names <- -jsonlite::fromJSON(readLines("data/lineage_data_full.json"),
#                              flatten=TRUE)
# 
# test <- jsonlite::fromJSON("https://github.com/cov-lineages/lineages-website/blob/master/_data/lineage_data.full.json?raw=true",
#                            flatten = TRUE,
#                            simplifyVector = TRUE)
# 
# test <- jsonlite::read_json("https://github.com/cov-lineages/lineages-website/blob/master/_data/lineage_data.full.json?raw=true",
#                            simplifyVector=TRUE)
# 
# 
# test %>%
#   flatten() %>% 
#   select(Lineage,)
#   unnest() %>%
#   glimpse()
# 
# 
# test %>% 
#   as.data.frame()


variant %>% 
  mutate(week_end_date = substr(week_ending, 1,10),
         week_end_date=ymd(week_end_date)) %>%
  filter(week_end_date==max(week_end_date)) %>%
  left_join(names,by=c('variant'='lineage')) 


```

```{r,eval=FALSE}
# https://dev.socrata.com/foundry/data.cdc.gov/jr58-6ysp


variant <- "https://data.cdc.gov/resource/jr58-6ysp.json?$limit=50000&$where=week_ending between '2021-02-18T00:00:00.000' and '2022-03-01T00:00:00.000'&usa_or_hhsregion=USA"
variant <- httr::GET(URLencode(variant))


# only go to the 6th because these are already weekly counts
# get the last couple weeks of 2021
variant <-jsonlite::fromJSON(
  httr::content(variant,
                as = "text",
                encoding = "UTF-8"),
  simplifyVector = TRUE,
  flatten = TRUE)  %>%
  as_tibble() 

saveRDS(variant, 'data/variant_prop.RDS')

```

```{r}
variant <- readRDS(here('data/variant_prop.RDS'))


# https://www.cdc.gov/coronavirus/2019-ncov/variants/variant-classifications.html
variant <- variant %>% 
  mutate(week_end_date = substr(week_ending, 1,10),
         week_end_date=ymd(week_end_date)) %>%
  mutate(variant_category = case_when(
     grepl("B[.]1[.]1[.]529|BA[.]1|BA[.]2|BA[.]4|BA[.]5", variant) ~ "Omicron",
     variant %in% c("B.1.621", "B.1.621.1") ~ "Mu",
     variant == "B.1.1.7" ~ "Alpha",
     grepl("B[.]1[.]351", variant) ~ "Beta",
     grepl("P.1", variant) ~"Gamma",
     grepl("B[.]1[.]617[.]2", variant) ~ "Delta",
     variant %in% c("B.1.427" ,"B.1.429") ~ "Epsilon",
     variant == "B.1.525" ~ "Eta",
     variant == "Other" ~ "Other"
  )) %>%
  mutate(share = as.numeric(share),
         creation_date = ymd(substr(creation_date,1,10))) %>%
  filter(modeltype == "weighted" & time_interval=="weekly") %>%
  group_by(variant, week_end_date, variant_category, time_interval) %>% 
  slice_max(n=1, order_by=creation_date) %>%
  group_by(variant_category, week_end_date, time_interval) %>%
  summarize(share =sum(share, na.rm=TRUE))






varpal <- c("#7BD8DA","#709f0f", "#e71761", "#9245c8", 
            "#97481c", "#5054b1", "#DA7BA8", "#26B392")

variant <- variant %>%
   filter(variant_category != "Other") %>%
  select(week_end_date, variant_category, share) %>%
  # week beginning rather than week end
  mutate(week = week_end_date - days(7)) %>%
  filter(!is.na(variant_category)) 

variant %>% ggplot(aes(x=week, y = share,
             color=variant_category, group = variant_category)) +
  geom_line(linewidth=1.1) +
  geom_point(alpha=.5, size=.8) +
  scale_color_manual(values=varpal) +
 # scale_color_brewer(palette="Set3") +
  theme_c() +
  scale_x_date(date_breaks="2 months", date_labels = "%b %Y") +
  labs(y = "Variant Proportion", x = "Date", color = "Variant") +
  guides(color =guide_legend(override.aes = list(linewidth=2))) +
  theme(legend.title = element_text(size = 18, face="bold"),
        axis.text.y = element_text(size = 15),
        axis.text.x=element_text(size=13),
        axis.title=element_text(size=16))


ggsave(here('thesis/figure/variant_prop.jpeg'), width =9, height=5, dpi=400)


```


# Ratio of Unobserved to Observed

Considering version using $P(S_1|\text{untested})$ centered at empirical value.


```{r}

subset %>% 
  ggplot(aes(x=date, ymin = exp_cases_lb/positive,
             ymax = exp_cases_ub/positive)) +
  geom_ribbon() +
  theme_c()+ 
  facet_wrap(~state)


```

```{r}

# max average ratio across all states
subset %>% 
  mutate(ratio =  exp_cases_median/positive) %>%
  group_by(biweek) %>%
  summarize(m = mean(ratio)) %>%
  filter(m==max(m)) %>%
  left_join(dates)

```



# Intervals by State and Biweek

```{r}

pal <- c("red", "#10BAC5", "#1B10C5", "#EFB719", "#900C3F")

names(pal) <- c("Covidestim",
                '$P(S_1|untested)$ Centered at Emp. Value',
                '$P(S_1|untested)$ and $\\beta$ Centered at Emp. Values',
               "$Priors\\,Do\\,Not\\,Vary\\,by\\,State\\,and\\,Date$",
               "$\\beta$ Centered at Emp. Value"
               )

```


## Only Michigan


```{r}

# pb max
m1 <- corrected %>%
  filter(state == "MI") %>%
  pull(exp_cases_ub) %>%
  max()


# covidestim max
m2 <- corrected %>%
  filter(state == "MI") %>%
  pull(infections.hi) %>%
  max()

m <- max(m1,m2)


varpal <- c("#7BD8DA","#709f0f", "#e71761", "#9245c8", 
            "#97481c", "#5054b1", "#DA7BA8", "#26B392")

corrected %>%
  filter(state == "MI" & version %in% c("v1","v4")) %>%
 # filter(state %in% sample(corrected$state,5)) %>%
  filter(biweek >=6) %>%
  group_by(biweek) %>%
  mutate(xmin = min(date),
         xmax = max(date)) %>%
  ungroup() %>%
   ggplot() +
  geom_ribbon(aes(x = date, 
             ymin = exp_cases_lb,
             ymax = exp_cases_ub,
             fill = vlabel),
             alpha = .5,
             show.legend=FALSE) +
  geom_ribbon(aes(x = date,
                  fill = 'Covidestim',
                  ymin = infections.lo,
                  ymax = infections.hi),
              alpha = .5) +
  facet_grid(~vlabel, scales = "free_y",
              labeller= labeller(vlabel =as_labeller(TeX, default=label_parsed))) +
  scale_x_date(date_breaks = "2 months", 
               date_labels = "%b %Y") +
  theme_c(axis.text.x = element_text(angle = 60, size = 16),
          plot.title=element_text(face = "bold",
                                  hjust = .5, 
                                  size = 24,
                                  margin=margin(5,5,15,5,'pt')),
          strip.background = element_rect(fill = "#393939"),
          strip.text = element_text(color =  "white", size = 16),
          strip.text.y = element_text(margin = margin(5,5,5,5,'pt'),
                                      size = 17,
                                      face="bold"),
          strip.text.x =  element_text(margin = margin(5,3,5,3,'pt'),
                                       face = "bold",
                                       size = 10),
          plot.subtitle = ggtext::element_markdown(size = 25,margin = margin(3,5,10,5,'pt'),
                                       face = "italic"),
          legend.position = "top",
          legend.text =element_text(size = 14),
          legend.title = element_text(size=16, face="bold")) +
  geom_line(aes(x=week, y=share*m,
                color =variant_category,
                group=variant_category),
            data=variant,
            linewidth=1.2) +
  scale_fill_manual(values =pal,
                    labels = TeX(names(pal)),
                     breaks='Covidestim',
                    name='')  +
  scale_y_continuous(sec.axis = sec_axis( trans=~./m, name="Variant Proportion"),
                     labels = comma) +
  labs(y = "Estimated Infections",
       title = paste0("Estimated Infections by Version in Michigan"),
       color = "SARS-CoV-2 Variant",
       x="Date") +
  guides(color = guide_legend(override.aes = list(linewidth =3),
                              ncol=2,title.position="top")) +
 # scale_color_brewer(palette="Accent") 
  scale_color_manual(values=varpal)



ggsave(here::here(paste0('thesis/figure/michigan_variant.pdf')), 
       height=10, width = 15, dpi=400)


```


## All States -- Break up into 2 groups

```{r}



states_all_versions <- corrected %>%
  select(state,version) %>%
  group_by(state) %>%
  summarize(n_versions = n_distinct(version)) %>% 
  filter(n_versions ==4) 


cat(paste0("### Number of states with 4 versions is: ", states_all_versions$state %>% unique() %>% length()))
cat(paste0("### Number of states with at least 1 versions is: ", corrected$state %>% unique() %>% length()))


end <- length(unique(states_all_versions$state))
n <- floor(end/2)

# first group
corrected %>%
  filter(state %in% states_all_versions$state[1:n]) %>%
 # filter(state %in% sample(corrected$state,5)) %>%
  filter(biweek >=6) %>%
  group_by(biweek) %>%
  mutate(xmin = min(date),
         xmax = max(date)) %>%
  ungroup() %>%
   ggplot() +
  geom_ribbon(aes(x = date, 
             ymin = exp_cases_lb,
             ymax = exp_cases_ub,
             fill = vlabel),
             alpha = .7,
             show.legend=FALSE) +
  geom_ribbon(aes(x = date,
                  fill = 'Covidestim',
                  ymin = infections.lo,
                  ymax = infections.hi),
              alpha = .7) +
   # geom_linerange(aes(xmin = xmin,
   #                    xmax=xmax,
   #                    y = positive,
   #                    color = 'obs')) +
  facet_grid(state~vlabel, scales = "free_y",
              labeller= labeller(vlabel =as_labeller(TeX, default=label_parsed))) +
  scale_y_continuous(labels = comma) +
  scale_x_date(date_breaks = "2 months", 
               date_labels = "%b %Y") +
  theme_c(axis.text.x = element_text(angle = 60, size = 16),
          plot.title=element_text(face = "bold",
                                  hjust = .5, 
                                  size = 20,
                                  margin=margin(5,5,15,5,'pt')),
          strip.background = element_rect(fill = "#393939"),
          strip.text = element_text(color =  "white", size = 16),
          strip.text.y = element_text(margin = margin(5,5,5,5,'pt'),
                                      size = 14,
                                      face="bold"),
          strip.text.x =  element_text(margin = margin(5,3,5,3,'pt'),
                                       face = "bold",
                                       size = 10),
          plot.subtitle = ggtext::element_markdown(size = 25,margin = margin(3,5,10,5,'pt'),
                                       face = "italic"),
          legend.position = "top",
          legend.text =element_text(size = 14)) +
  scale_fill_manual(values =pal,
                    labels = TeX(names(pal)),
                    name='',
                    breaks="Covidestim")  +
  labs(y = "Estimated Infections",
       title = paste0("Estimated Infections by Version Across the United States")) +
  scale_color_manual(values = c('obs' = 'red'), labels = 'Positive Tests',
                     name = '') +
  guides(color = guide_legend(override.aes = list(linewidth =2),
                              nrow=2,
                              byrow=TRUE))



ggsave(here::here(paste0('thesis/figure/state_comp_covidestim1.pdf')), 
       height=24, width = 17, dpi=400)



corrected %>%
  filter(state %in% states_all_versions$state[n+1:end]) %>%
 # filter(state %in% sample(corrected$state,5)) %>%
  filter(biweek >=6) %>%
  group_by(biweek) %>%
  mutate(xmin = min(date),
         xmax = max(date)) %>%
  ungroup() %>%
   ggplot() +
  geom_ribbon(aes(x = date, 
             ymin = exp_cases_lb,
             ymax = exp_cases_ub,
             fill = vlabel),
             alpha = .6,
             show.legend=FALSE) +
  geom_ribbon(aes(x = date,
                  fill = 'Covidestim',
                  ymin = infections.lo,
                  ymax = infections.hi),
              alpha = .8) +
   # geom_linerange(aes(xmin = xmin,
   #                    xmax=xmax,
   #                    y = positive,
   #                    color = 'obs')) +
  facet_grid(state~vlabel, scales = "free_y",
              labeller= labeller(vlabel =as_labeller(TeX, default=label_parsed))) +
  scale_y_continuous(labels = comma) +
  scale_x_date(date_breaks = "2 months", 
               date_labels = "%b %Y") +
  theme_c(axis.text.x = element_text(angle = 60, size = 16),
          plot.title=element_text(face = "bold",
                                  hjust = .5, 
                                  size = 20,
                                  margin=margin(5,5,15,5,'pt')),
          strip.background = element_rect(fill = "#393939"),
          strip.text = element_text(color =  "white", size = 16),
          strip.text.y = element_text(margin = margin(5,5,5,5,'pt'),
                                      size = 14,
                                      face="bold"),
          strip.text.x =  element_text(margin = margin(5,3,5,3,'pt'),
                                       face = "bold",
                                       size = 10),
          plot.subtitle = ggtext::element_markdown(size = 25,margin = margin(3,5,10,5,'pt'),
                                       face = "italic"),
          legend.position = "top",
          legend.text =element_text(size = 14)) +
  scale_fill_manual(values =pal,
                    labels = TeX(names(pal)),
                    name='',
                    breaks="Covidestim")  +
  labs(y = "Estimated Infections",
       title = paste0("Estimated Infections by Version Across the United States")) +
  scale_color_manual(values = c('obs' = 'red'), labels = 'Positive Tests',
                     name = '') +
  guides(color = guide_legend(override.aes = list(linewidth =2),
                              nrow=2,
                              byrow=TRUE),
         fill="none")


ggsave(here::here('thesis/figure/state_comp_covidestim2.pdf'), 
       height=24, width = 17, dpi=400)



```


```{r}

#######################
# for presentation
#######################
corrected %>%
  filter(state %in% c("MA", "MI")) %>%
 # filter(state %in% sample(corrected$state,5)) %>%
  filter(biweek >=6) %>%
  group_by(biweek) %>%
  mutate(xmin = min(date),
         xmax = max(date)) %>%
  ungroup() %>%
   ggplot() +
  geom_ribbon(aes(x = date, 
             ymin = exp_cases_lb,
             ymax = exp_cases_ub,
             fill = vlabel),
             alpha = .7,
             show.legend=FALSE) +
  geom_ribbon(aes(x = date,
                  fill = 'Covidestim',
                  ymin = infections.lo,
                  ymax = infections.hi),
              alpha = .7) +
   # geom_linerange(aes(xmin = xmin,
   #                    xmax=xmax,
   #                    y = positive,
   #                    color = 'obs')) +
  facet_grid(state~vlabel, scales = "free_y",
              labeller= labeller(vlabel =as_labeller(TeX, default=label_parsed))) +
  scale_y_continuous(labels = comma) +
  scale_x_date(date_breaks = "2 months", 
               date_labels = "%b %Y") +
  theme_c(axis.text.x = element_text(angle = 40, size = 10),
          axis.text.y = element_text( size = 7),
          plot.title=element_text(face = "bold",
                                  hjust = .5, 
                                  size = 20,
                                  margin=margin(5,5,15,5,'pt')),
          strip.background = element_rect(fill = "#393939"),
          strip.text = element_text(color =  "white", size = 16),
          strip.text.y = element_text(margin = margin(5,5,5,5,'pt'),
                                      size = 14,
                                      face="bold"),
          strip.text.x =  element_text(margin = margin(5,3,5,3,'pt'),
                                       face = "bold",
                                       size = 10),
          plot.subtitle = ggtext::element_markdown(size = 25,margin = margin(3,5,10,5,'pt'),
                                       face = "italic"),
          legend.position = "top",
          legend.text =element_text(size = 14)) +
  scale_fill_manual(values =pal,
                    breaks='Covidestim',
                    labels = TeX(names(pal)),
                    name='')  +
  labs(y = "Estimated Infections",
       title = paste0("Estimated Infections by Version (State Level)")) 


ggsave(here('presentation/figure/state_level_mi_ma.jpeg'), width =13, height=9)

```



```{r}

ratios <- corrected %>%
  filter(vlabel == "$P(S_1|untested)$ Centered at Emp. Value") %>% 
 # filter(state %in% sample(unique(corrected$state),5)) %>%
  mutate(ratio_undetected_lb = exp_cases_lb/ positive,
         ratio_undected = exp_cases_median/positive,
         ratio_undetected_ub = exp_cases_ub/ positive) %>%
  group_by(state) %>%
  mutate(m_ratio = median(ratio_undected)) %>%
  ungroup() %>%
  mutate(state=fct_reorder(state,m_ratio)) %>%
  arrange(state)

states_ordered <-ratios$state %>% unique()

ratios %>%
 # filter(state %in% states_ordered[1:n])  %>%
  ggplot(aes(x=date,ymin=ratio_undetected_lb, ymax=ratio_undetected_ub)) +
  geom_ribbon(
              alpha = .8) +
   # geom_linerange(aes(xmin = xmin,
   #                    xmax=xmax,
   #                    y = positive,
   #                    color = 'obs')) +
  facet_wrap(~state,
              labeller= labeller(vlabel =as_labeller(TeX, default=label_parsed)),
             ncol = 5) +
  scale_y_continuous(labels = comma) +
  scale_x_date(date_breaks = "2 months", 
               date_labels = "%b %Y") +
  theme_c(axis.text.x = element_text(angle = 60, size = 16),
          plot.title=element_text(face = "bold",
                                  hjust = .5, 
                                  size = 20,
                                  margin=margin(5,5,15,5,'pt')),
          strip.background = element_rect(fill = "#393939"),
          strip.text = element_text(color =  "white", size = 16),
          strip.text.y = element_text(margin = margin(5,5,5,5,'pt'),
                                      size = 14,
                                      face="bold"),
          strip.text.x =  element_text(margin = margin(5,3,5,3,'pt'),
                                       face = "bold",
                                       size = 10),
          plot.subtitle = ggtext::element_markdown(size = 25,margin = margin(3,5,10,5,'pt'),
                                       face = "italic"),
          legend.position = "top",
          legend.text =element_text(size = 14)) +
  scale_fill_manual(values =pal,
                    labels = TeX(names(pal)),
                    name='')  +
  labs(y = "Ratio of Estimated Infections to Observed Cases",
       title = paste0("Ratio of Estimated to Observed Cases")) +
  scale_color_manual(values = c('obs' = 'red'), labels = 'Positive Tests',
                     name = '') +
  guides(color = guide_legend(override.aes = list(linewidth =2),
                              nrow=2,
                              byrow=TRUE))






```


